### ISSUE TITLE
After setting up WAF, I still have the issue

### ISSUE THREAD

**Issue by AngusHo53** [Link0Darck/cloudflare#1]
Hello, I followed your instructions and set up WAF rules in cloudflare and selected "Skip".  
But the issue still exists. When I post a link to a image of my website in discord, it still displays "poop".  
I'm pretty sure the image link is correct (when I paste it in the browser or get it from postman, he can access the image directly).  
Is there any other solution? Thank you!

**Comment by Link0Darck** [comment]
Hello,
I forgot to specify something, I will remedy that.
but tell me more about your problem

**Comment by Link0Darck** [comment]
Hello,
I edited to see if you have the same thing.
[Cloudflare](https://github.com/Link0Darck/cloudflare/blob/main/Discord/README.md)
Sincerely

**Comment by AngusHo53** [comment]
Thank you for your edit. 
When I set up cloudflare according to your document, discord still cannot display the image through the image url.
![image](https://github.com/Link0Darck/cloudflare/assets/18003181/e9e0efeb-4f97-4fba-b327-5c37b157a862)


My cloudflare settings are as follows:
![image](https://github.com/Link0Darck/cloudflare/assets/18003181/053a297c-9db0-4b29-9939-1f88094bd9c1)
![image](https://github.com/Link0Darck/cloudflare/assets/18003181/9ae60984-445f-4cc7-a6ea-66d852bda4c8)

My image url is this. When you open it in the browser, you can get the image correctly. But it fails on discord.
https://i.meee.com.tw/HAkGHdl.png

Then I found that there was a discord skip in cloudflare's WAF.
![image](https://github.com/Link0Darck/cloudflare/assets/18003181/197084fb-79e1-4062-bb36-ce6c4ef70e63)
So I'm not sure why it still fails on discord.

**Comment by Link0Darck** [comment]
Could this be due to the cloudflare and Discord cache?

**Comment by AngusHo53** [comment]
I tried clearing cloudflare's cache but it still doesn't show up. 
Is there any way I can clear discord's cache?

**Comment by Link0Darck** [comment]
Hello,
For my part it works correctly but what do you have in Cloudflare WAF rule because I think there is another rule which blocks your site or also deactivates the option : ( **Bot Fight Mode** )

**Example that it works on my side :**
[https://inari.neko-world.ovh/assets/divertissement.png](https://inari.neko-world.ovh/assets/divertissement.png)

**Comment by AngusHo53** [comment]
It is normal for your image url to be posted in discord. I have set up Bot Fight Mode, but I am not sure what the consequences will be if it is turned off (I often see reports of Bot Fight Mode in the report).

**Comment by AngusHo53** [comment]
I turned off Bot Fight Mode but the problem still exists. Have you set IP Access Rules?
![image](https://github.com/Link0Darck/cloudflare/assets/18003181/babe0521-bbd9-4a26-a9d7-f28fe237b4b3)

**Comment by AngusHo53** [comment]
I found the reason, because I set CORS headers in my cloudflare R2 bucket.
I'm still thinking about how to modify it.
Thanks a lot!
![image](https://github.com/Link0Darck/cloudflare/assets/18003181/9a3d1909-26f3-43b1-9a93-12a021800d2a)
